### ISSUE TITLE
testing the `Styler` against a Korean Wikipedia article

### ISSUE THREAD

**Issue by eubinean** [eubinean/politely#90]
## Why? 

Augmentation 도구로 쓰고 싶다면 위키피디아 문서 하나 정도는 자유자재로 formality를 변경할 수 있어야 한다. 한번 해보자.

**Comment by eubinecto** [comment]
지금 [당장 해결할 수 없는 오류](https://github.com/bab2min/kiwipiepy/issues/87#issue-1293273032)가 발생. Segmentation Fault라 문제의 원인을 파악하는 것이 불가능하다. 이슈분석을 부탁드리고 일단 다른 것부터 해결해보자.

**Comment by eubinecto** [comment]
`EFNotIncludedError`는 제거해야할 듯 하다 |
--- | 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/56193069/177741235-4e182a5e-2396-4e80-86e6-9373420411d5.png">  |

`split_into_sents`를 해도, 당연히  이렇게 EF가 없는 경우가 생긴다.  일반화를 할 수 없는 가정이다.

**Comment by eubinecto** [comment]
이에요 / 예요 / 에요  -> 구분하는 conjugate 규칙이 필요할 것 같다 | 
--- | 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/56193069/177767456-acb49719-e7c2-45e8-9086-ce2ababa9f72.png"> |
